inkscape img/svg/blackbishop.svg --export-type=png --export-filename=img/png/blackbishop.png
inkscape img/svg/blackking.svg --export-type=png --export-filename=img/png/blackking.png
inkscape img/svg/blackknight.svg --export-type=png --export-filename=img/png/blackknight.png
inkscape img/svg/blackpawn.svg --export-type=png --export-filename=img/png/blackpawn.png
inkscape img/svg/blackpiece.svg --export-type=png --export-filename=img/png/blackpiece.png
inkscape img/svg/blackqueen.svg --export-type=png --export-filename=img/png/blackqueen.png
inkscape img/svg/blackrook.svg --export-type=png --export-filename=img/png/blackrook.png
inkscape img/svg/blacksmallking.svg --export-type=png --export-filename=img/png/blacksmallking.png
inkscape img/svg/blacksmallpiece.svg --export-type=png --export-filename=img/png/blacksmallpiece.png
inkscape img/svg/chess.svg --export-type=png --export-filename=img/png/chess.png
inkscape img/svg/go9.svg --export-type=png --export-filename=img/png/go9.png
inkscape img/svg/gomoku.svg --export-type=png --export-filename=img/png/gomoku.png
inkscape img/svg/morris.svg --export-type=png --export-filename=img/png/morris.png
inkscape img/svg/selection.svg --export-type=png --export-filename=img/png/selection.png
inkscape img/svg/whitebishop.svg --export-type=png --export-filename=img/png/whitebishop.png
inkscape img/svg/whiteking.svg --export-type=png --export-filename=img/png/whiteking.png
inkscape img/svg/whiteknight.svg --export-type=png --export-filename=img/png/whiteknight.png
inkscape img/svg/whitepawn.svg --export-type=png --export-filename=img/png/whitepawn.png
inkscape img/svg/whitepiece.svg --export-type=png --export-filename=img/png/whitepiece.png
inkscape img/svg/whitequeen.svg --export-type=png --export-filename=img/png/whitequeen.png
inkscape img/svg/whiterook.svg --export-type=png --export-filename=img/png/whiterook.png
inkscape img/svg/whitesmallking.svg --export-type=png --export-filename=img/png/whitesmallking.png
inkscape img/svg/whitesmallpiece.svg --export-type=png --export-filename=img/png/whitesmallpiece.png
cd src
javac -d ../bin CheckersState.java
javac -d ../bin ChessState.java
javac -d ../bin Go9State.java
javac -d ../bin GomokuState.java
javac -d ../bin MainWindow.java
javac -d ../bin MorrisState.java