inkscape svg/blackamazon.svg --export-type=png --export-filename=png/blackamazon.png
inkscape svg/blackarchbishop.svg --export-type=png --export-filename=png/blackarchbishop.png
inkscape svg/blackbishop.svg --export-type=png --export-filename=png/blackbishop.png
inkscape svg/blackcentaur.svg --export-type=png --export-filename=png/blackcentaur.png
inkscape svg/blackchancellor.svg --export-type=png --export-filename=png/blackchancellor.png
inkscape svg/blackdragon.svg --export-type=png --export-filename=png/blackdragon.png
inkscape svg/blackking.svg --export-type=png --export-filename=png/blackking.png
inkscape svg/blackknight.svg --export-type=png --export-filename=png/blackknight.png
inkscape svg/blacklargepiece.svg --export-type=png --export-filename=png/blacklargepiece.png
inkscape svg/blackpawn.svg --export-type=png --export-filename=png/blackpawn.png
inkscape svg/blackpiece.svg --export-type=png --export-filename=png/blackpiece.png
inkscape svg/blackqueen.svg --export-type=png --export-filename=png/blackqueen.png
inkscape svg/blackrook.svg --export-type=png --export-filename=png/blackrook.png
inkscape svg/blacksmallking.svg --export-type=png --export-filename=png/blacksmallking.png
inkscape svg/blacksmallpiece.svg --export-type=png --export-filename=png/blacksmallpiece.png
inkscape svg/capablanca.svg --export-type=png --export-filename=png/capablanca.png
inkscape svg/chess.svg --export-type=png --export-filename=png/chess.png
inkscape svg/grandchess.svg --export-type=png --export-filename=png/grandchess.png
inkscape svg/morris.svg --export-type=png --export-filename=png/morris.png
inkscape svg/reversi.svg --export-type=png --export-filename=png/reversi.png
inkscape svg/selection.svg --export-type=png --export-filename=png/selection.png
inkscape svg/smallselection.svg --export-type=png --export-filename=png/smallselection.png
inkscape svg/tictactoe.svg --export-type=png --export-filename=png/tictactoe.png
inkscape svg/whiteamazon.svg --export-type=png --export-filename=png/whiteamazon.png
inkscape svg/whitearchbishop.svg --export-type=png --export-filename=png/whitearchbishop.png
inkscape svg/whitebishop.svg --export-type=png --export-filename=png/whitebishop.png
inkscape svg/whitecentaur.svg --export-type=png --export-filename=png/whitecentaur.png
inkscape svg/whitechancellor.svg --export-type=png --export-filename=png/whitechancellor.png
inkscape svg/whitedragon.svg --export-type=png --export-filename=png/whitedragon.png
inkscape svg/whiteking.svg --export-type=png --export-filename=png/whiteking.png
inkscape svg/whiteknight.svg --export-type=png --export-filename=png/whiteknight.png
inkscape svg/whitelargepiece.svg --export-type=png --export-filename=png/whitelargepiece.png
inkscape svg/whitepawn.svg --export-type=png --export-filename=png/whitepawn.png
inkscape svg/whitepiece.svg --export-type=png --export-filename=png/whitepiece.png
inkscape svg/whitequeen.svg --export-type=png --export-filename=png/whitequeen.png
inkscape svg/whiterook.svg --export-type=png --export-filename=png/whiterook.png
inkscape svg/whitesmallking.svg --export-type=png --export-filename=png/whitesmallking.png
inkscape svg/whitesmallpiece.svg --export-type=png --export-filename=png/whitesmallpiece.png
